"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { useParams } from "next/navigation";
import { Printer, Download, RotateCcw, ChevronLeft, RefreshCw, ChevronDown, ChevronUp, AlertCircle, Loader2 } from "lucide-react";
import Link from "next/link";

// ─── Types ─────────────────────────────────────────────────────────

interface TemplateVariable {
  key: string;
  label: string;
  exampleText: string;
  category: string;
  isBarcode: boolean;
  isQR: boolean;
}

interface FieldDef {
  key: string;
  label: string;
  small?: boolean;
  textarea?: boolean;
}

interface FieldGroup {
  title: string;
  fields: FieldDef[];
}

interface TemplateMeta {
  id: number;
  name: string;
  type: string;
  size: string;
  pageWidth: number;
  pageHeight: number;
  elementCount: number;
}

// ─── Component ─────────────────────────────────────────────────────

export default function TemplatePreviewPage() {
  const params = useParams();
  const templateId = params.id as string;

  // Template metadata + variables from API
  const [templateMeta, setTemplateMeta] = useState<TemplateMeta | null>(null);
  const [variables, setVariables] = useState<TemplateVariable[]>([]);
  const [fieldGroups, setFieldGroups] = useState<FieldGroup[] | null>(null);
  const [useSpecializedRenderer, setUseSpecializedRenderer] = useState(false);
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [defaultData, setDefaultData] = useState<Record<string, string>>({});
  const [loadingTemplate, setLoadingTemplate] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);

  // PDF preview state
  const [loading, setLoading] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Rx Label specific state
  const [fillId, setFillId] = useState("");

  // UI state
  const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(new Set());
  const hasAutoGenerated = useRef(false);

  // Determine if this is an Rx Label template
  const isRxLabel = templateMeta?.type === "Rx Label";

  // Load template metadata + variables on mount
  useEffect(() => {
    async function loadTemplate() {
      try {
        const res = await fetch(`/api/labels/template?id=${templateId}`);
        if (!res.ok) {
          const data = await res.json();
          throw new Error(data.error || "Failed to load template");
        }
        const json = await res.json();
        setTemplateMeta(json.template);

        if (json.fieldGroups && json.useSpecializedRenderer) {
          // Specialized renderer path (compound labels, etc.)
          setFieldGroups(json.fieldGroups);
          setUseSpecializedRenderer(true);
          setFormData(json.defaultData || {});
          setDefaultData(json.defaultData || {});
        } else {
          // Generic renderer path (auto-detected variables)
          setVariables(json.variables || []);
          setFormData(json.defaultData || {});
          setDefaultData(json.defaultData || {});
        }
      } catch (e) {
        setLoadError(e instanceof Error ? e.message : "Failed to load template");
      } finally {
        setLoadingTemplate(false);
      }
    }
    loadTemplate();
  }, [templateId]);

  const updateField = useCallback((key: string, value: string) => {
    setFormData((prev) => ({ ...prev, [key]: value }));
  }, []);

  const toggleGroup = useCallback((groupKey: string) => {
    setCollapsedGroups((prev) => {
      const next = new Set(prev);
      if (next.has(groupKey)) next.delete(groupKey);
      else next.add(groupKey);
      return next;
    });
  }, []);

  // Generate PDF preview
  const generatePreview = useCallback(async () => {
    if (!templateId || !templateMeta) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/labels/template", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ templateId: Number(templateId), data: formData }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to generate preview");
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      if (pdfUrl) URL.revokeObjectURL(pdfUrl);
      setPdfUrl(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }, [templateId, templateMeta, formData, pdfUrl]);

  // Load from Fill ID (Rx Label only)
  const generateFromFill = async () => {
    if (!fillId.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/labels/compound?fillId=${encodeURIComponent(fillId.trim())}`);
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to generate label from fill");
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      if (pdfUrl) URL.revokeObjectURL(pdfUrl);
      setPdfUrl(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate preview when form data changes (debounced)
  useEffect(() => {
    if (loadingTemplate || !templateMeta) return;
    const timeout = setTimeout(
      () => generatePreview(),
      hasAutoGenerated.current ? 600 : 0
    );
    hasAutoGenerated.current = true;
    return () => clearTimeout(timeout);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [formData, templateMeta, loadingTemplate]);

  const resetToDefaults = () => {
    setFormData({ ...defaultData });
  };

  const downloadPdf = () => {
    if (!pdfUrl) return;
    const a = document.createElement("a");
    a.href = pdfUrl;
    a.download = `${templateMeta?.name || "template"}.pdf`;
    a.click();
  };

  const printPdf = () => {
    if (!pdfUrl) return;
    const win = window.open(pdfUrl, "_blank");
    if (win) {
      win.addEventListener("load", () => win.print());
    }
  };

  // Group variables by category (for generic path)
  const groupedVars = variables.reduce<Record<string, TemplateVariable[]>>((acc, v) => {
    if (!acc[v.category]) acc[v.category] = [];
    acc[v.category].push(v);
    return acc;
  }, {});

  const categories = Object.keys(groupedVars).sort();

  // Compute iframe dimensions based on page orientation
  const isLandscape = templateMeta
    ? templateMeta.pageHeight > templateMeta.pageWidth
      ? true  // portrait template rendered as landscape
      : templateMeta.pageWidth > templateMeta.pageHeight
    : false;

  const iframeScale = 96; // px per inch for preview
  const iframeWidth = templateMeta
    ? isLandscape
      ? Math.round(Math.max(templateMeta.pageWidth, templateMeta.pageHeight) * iframeScale)
      : Math.round(templateMeta.pageWidth * iframeScale)
    : 768;
  const iframeHeight = templateMeta
    ? isLandscape
      ? Math.round(Math.min(templateMeta.pageWidth, templateMeta.pageHeight) * iframeScale)
      : Math.round(templateMeta.pageHeight * iframeScale)
    : 384;

  // ── Loading state ──
  if (loadingTemplate) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-[var(--green-700)] animate-spin mx-auto mb-3" />
          <p className="text-sm text-[var(--text-muted)]">Loading template...</p>
        </div>
      </div>
    );
  }

  // ── Error state ──
  if (loadError) {
    return (
      <div className="px-6 py-12 text-center">
        <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-3" />
        <h2 className="text-lg font-semibold text-gray-900 mb-2">Template Not Found</h2>
        <p className="text-sm text-gray-500 mb-4">{loadError}</p>
        <p className="text-xs text-gray-400 mb-6">
          This template may need to be imported from DRX first.
        </p>
        <Link
          href="/settings/print-templates"
          className="inline-flex items-center gap-1.5 px-4 py-2 text-sm text-[var(--green-700)] border border-[var(--green-700)] rounded-md hover:bg-[var(--green-50)] transition-colors no-underline"
        >
          <ChevronLeft className="w-4 h-4" /> Back to Templates
        </Link>
      </div>
    );
  }

  // ── Render the specialized (fieldGroups) editor ──
  const renderSpecializedEditor = () => {
    if (!fieldGroups) return null;
    return (
      <>
        {fieldGroups.map((group) => {
          const isCollapsed = collapsedGroups.has(group.title);
          return (
            <div key={group.title} className="bg-white rounded-lg border border-[var(--border)]">
              <button
                onClick={() => toggleGroup(group.title)}
                className="w-full px-3 py-2 flex items-center justify-between text-left hover:bg-gray-50 transition-colors rounded-t-lg"
              >
                <span className="text-xs font-semibold text-[var(--text-primary)] uppercase tracking-wide">
                  {group.title}
                  <span className="ml-2 text-[10px] text-[var(--text-muted)] font-normal normal-case">
                    ({group.fields.length} field{group.fields.length !== 1 ? "s" : ""})
                  </span>
                </span>
                {isCollapsed ? (
                  <ChevronDown className="w-3.5 h-3.5 text-[var(--text-muted)]" />
                ) : (
                  <ChevronUp className="w-3.5 h-3.5 text-[var(--text-muted)]" />
                )}
              </button>
              {!isCollapsed && (
                <div className="px-3 pb-3 grid grid-cols-2 gap-x-2 gap-y-2">
                  {group.fields.map((field) => (
                    <div key={field.key} className={field.textarea ? "col-span-2" : field.small ? "col-span-1" : "col-span-2"}>
                      <label className="block text-[10px] font-medium text-[var(--text-muted)] mb-0.5 uppercase tracking-wide">
                        {field.label}
                      </label>
                      {field.textarea ? (
                        <textarea
                          value={formData[field.key] || ""}
                          onChange={(e) => updateField(field.key, e.target.value)}
                          rows={3}
                          className="w-full px-2 py-1.5 border border-[var(--border)] rounded text-xs focus:outline-none focus:ring-1 focus:ring-[var(--green-200)] focus:border-[var(--green-700)] resize-none"
                        />
                      ) : (
                        <input
                          type="text"
                          value={formData[field.key] || ""}
                          onChange={(e) => updateField(field.key, e.target.value)}
                          className="w-full px-2 py-1.5 border border-[var(--border)] rounded text-xs focus:outline-none focus:ring-1 focus:ring-[var(--green-200)] focus:border-[var(--green-700)]"
                        />
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}

        {/* Warning Flags for Rx Labels with specialized renderer */}
        {isRxLabel && (
          <div className="bg-white rounded-lg border border-[var(--border)] px-3 py-3">
            <span className="text-xs font-semibold text-[var(--text-primary)] uppercase tracking-wide block mb-2">Warning Flags</span>
            <div className="flex items-center gap-4">
              <label className="flex items-center gap-2 text-xs text-[var(--text-secondary)] cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.noClaimWarning === "true"}
                  onChange={(e) => updateField("noClaimWarning", e.target.checked ? "true" : "false")}
                  className="accent-[var(--green-700)]"
                />
                NO PAID CLAIM
              </label>
              <label className="flex items-center gap-2 text-xs text-[var(--text-secondary)] cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.holdWarning === "true"}
                  onChange={(e) => updateField("holdWarning", e.target.checked ? "true" : "false")}
                  className="accent-[var(--green-700)]"
                />
                HOLD
              </label>
            </div>
          </div>
        )}
      </>
    );
  };

  // ── Render the generic (variables-based) editor ──
  const renderGenericEditor = () => {
    if (variables.length === 0) {
      return (
        <div className="bg-white rounded-lg border border-[var(--border)] p-6 text-center">
          <AlertCircle className="w-8 h-8 text-[var(--text-muted)] mx-auto mb-2 opacity-40" />
          <p className="text-xs text-[var(--text-muted)]">
            No editable variables found in this template.
          </p>
        </div>
      );
    }

    return categories.map((category) => {
      const vars = groupedVars[category];
      const isCollapsed = collapsedGroups.has(category);
      return (
        <div key={category} className="bg-white rounded-lg border border-[var(--border)]">
          <button
            onClick={() => toggleGroup(category)}
            className="w-full px-3 py-2 flex items-center justify-between text-left hover:bg-gray-50 transition-colors rounded-t-lg"
          >
            <span className="text-xs font-semibold text-[var(--text-primary)] uppercase tracking-wide">
              {category}
              <span className="ml-2 text-[10px] text-[var(--text-muted)] font-normal normal-case">
                ({vars.length} field{vars.length !== 1 ? "s" : ""})
              </span>
            </span>
            {isCollapsed ? (
              <ChevronDown className="w-3.5 h-3.5 text-[var(--text-muted)]" />
            ) : (
              <ChevronUp className="w-3.5 h-3.5 text-[var(--text-muted)]" />
            )}
          </button>
          {!isCollapsed && (
            <div className="px-3 pb-3 space-y-2">
              {vars.map((v) => (
                <div key={v.key}>
                  <label className="block text-[10px] font-medium text-[var(--text-muted)] mb-0.5 uppercase tracking-wide">
                    {v.label}
                    {(v.isBarcode || v.isQR) && (
                      <span className="ml-1 text-[9px] text-blue-500 font-normal normal-case">
                        ({v.isBarcode ? "barcode" : "QR"})
                      </span>
                    )}
                  </label>
                  <input
                    type="text"
                    value={formData[v.key] || ""}
                    onChange={(e) => updateField(v.key, e.target.value)}
                    placeholder={v.exampleText || v.key}
                    className="w-full px-2 py-1.5 border border-[var(--border)] rounded text-xs focus:outline-none focus:ring-1 focus:ring-[var(--green-200)] focus:border-[var(--green-700)]"
                  />
                </div>
              ))}
            </div>
          )}
        </div>
      );
    });
  };

  // Count fields for status bar
  const fieldCount = useSpecializedRenderer
    ? (fieldGroups || []).reduce((sum, g) => sum + g.fields.length, 0)
    : variables.length;
  const groupCount = useSpecializedRenderer
    ? (fieldGroups || []).length
    : categories.length;

  return (
    <div>
      {/* Breadcrumb */}
      <div className="px-6 py-2.5 text-xs text-[var(--text-muted)] flex items-center gap-1.5">
        <a href="/dashboard" className="text-[var(--green-700)] no-underline font-medium hover:underline">Home</a>
        <span className="text-[#c5d5c9]">&rsaquo;</span>
        <Link href="/settings/print-templates" className="text-[var(--green-700)] no-underline font-medium hover:underline">Print Templates</Link>
        <span className="text-[#c5d5c9]">&rsaquo;</span>
        <span className="text-[var(--text-secondary)] font-semibold">{templateMeta?.name || "Template"}</span>
      </div>

      <div className="px-6 pb-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <Link href="/settings/print-templates" className="text-[var(--green-700)] hover:text-[var(--green-800)] inline-flex items-center gap-1 text-sm no-underline">
              <ChevronLeft className="w-4 h-4" /> Back
            </Link>
            <h1 className="text-lg font-bold text-[var(--text-primary)]">{templateMeta?.name}</h1>
            <span className="text-xs bg-[var(--green-50)] text-[var(--green-700)] px-2 py-0.5 rounded-full font-medium">
              {templateMeta?.size} {templateMeta?.type}
            </span>
            <span className="text-[10px] text-[var(--text-muted)] bg-gray-100 px-2 py-0.5 rounded">
              {templateMeta?.elementCount} elements
            </span>
            {useSpecializedRenderer && (
              <span className="text-[10px] text-blue-600 bg-blue-50 px-2 py-0.5 rounded">
                Specialized Renderer
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button onClick={resetToDefaults} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-[var(--border)] rounded-md hover:bg-gray-50 transition-colors">
              <RotateCcw className="w-3.5 h-3.5" /> Reset
            </button>
            {pdfUrl && (
              <>
                <button onClick={downloadPdf} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-[var(--border)] rounded-md hover:bg-gray-50 transition-colors">
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
                <button onClick={printPdf} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-[var(--border)] rounded-md hover:bg-gray-50 transition-colors">
                  <Printer className="w-3.5 h-3.5" /> Print
                </button>
              </>
            )}
          </div>
        </div>

        {/* Load from Fill bar (Rx Label only) + Status */}
        <div className="bg-white rounded-lg border border-[var(--border)] p-3 mb-4 flex items-center gap-3 flex-wrap">
          {isRxLabel && (
            <div className="flex items-center gap-2">
              <input
                type="text"
                placeholder="Fill ID for real data..."
                value={fillId}
                onChange={(e) => setFillId(e.target.value)}
                className="px-3 py-2 border border-[var(--border)] rounded-md text-sm w-52 focus:outline-none focus:ring-2 focus:ring-[var(--green-200)] focus:border-[var(--green-700)]"
              />
              <button
                onClick={generateFromFill}
                disabled={loading || !fillId.trim()}
                className="inline-flex items-center gap-1.5 px-3 py-2 border border-[var(--green-700)] text-[var(--green-700)] rounded-md text-sm font-medium hover:bg-[var(--green-50)] disabled:opacity-50 transition-colors"
              >
                <RefreshCw className="w-3.5 h-3.5" /> Load Fill
              </button>
            </div>
          )}
          <span className="text-xs text-[var(--text-muted)]">
            DRX Template #{templateMeta?.id} &middot; {fieldCount} fields &middot; {groupCount} groups
          </span>
          {loading && (
            <span className="text-xs text-[var(--text-muted)] animate-pulse ml-auto">Updating preview...</span>
          )}
          {error && (
            <span className="text-sm text-red-600 ml-auto">{error}</span>
          )}
        </div>

        {/* Two-column: Editor + Preview */}
        <div className="flex gap-4" style={{ minHeight: "calc(100vh - 220px)" }}>
          {/* Left: Editor Fields */}
          <div className="w-[420px] flex-shrink-0 overflow-y-auto space-y-3" style={{ maxHeight: "calc(100vh - 220px)" }}>
            {useSpecializedRenderer ? renderSpecializedEditor() : renderGenericEditor()}
          </div>

          {/* Right: PDF Preview */}
          <div className="flex-1 min-w-0">
            {pdfUrl ? (
              <div className="bg-white rounded-lg border border-[var(--border)] overflow-hidden h-full flex flex-col">
                <div className="bg-gray-50 px-4 py-2 border-b border-[var(--border)] flex items-center justify-between flex-shrink-0">
                  <span className="text-xs font-medium text-[var(--text-muted)]">Label Preview</span>
                  <span className="text-xs text-[var(--text-muted)]">{templateMeta?.size}</span>
                </div>
                <div className="flex-1 flex justify-center items-start p-4 bg-gray-100 overflow-auto">
                  <iframe
                    src={pdfUrl}
                    className="bg-white shadow-lg"
                    style={{
                      width: `${Math.min(iframeWidth, 900)}px`,
                      height: `${Math.min(iframeHeight, 1200)}px`,
                      border: "none",
                    }}
                    title="Template Preview"
                  />
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-lg border border-[var(--border)] h-full flex flex-col items-center justify-center text-center p-8">
                <Printer className="w-16 h-16 text-[var(--text-muted)] mb-4 opacity-30" />
                <p className="text-[var(--text-muted)] text-sm mb-1">
                  {loadingTemplate ? "Loading template..." : "Loading label preview..."}
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
